import { Providers } from "@/context/providers"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Header from "./components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Conexion Celestial Radio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "flex flex-col max-h-screen")}>
        <Providers>
          <Header></Header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
